# Ansible Azure Pipeline
trigger:
 - main

pool:
   name: 'default'

steps:

 - script: |
         echo "First pipeline script"
         echo "Another line of code"

 - script: |
         sudo apt-get update -y
         sudo apt install -y ansible
         ansible --version
   displayName: "Installing Ansible"