name: Ansible-GitHub actions
on: push
jobs:
  repo_updated:
    runs-on: self-hosted
    steps:
     - uses: actions/checkout@main
  install_ansible:
    needs: repo_updated
    runs-on: self-hosted
    steps:
      - name: Installing ansible
        run: |
          sudo apt-get update -y
          sudo apt install -y ansible
          ansible --version

  install_ansible_lint:
    needs: repo_updated
    runs-on: self-hosted
    steps:
      - name: Installing ansible-lint
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible-lint
          ansible-lint --version

  run_ansible_lint:
    needs: [install_ansible, install_ansible_lint]
    runs-on: self-hosted
    steps:
      - name: Linting ansible playbooks
        run: ansible-lint

  install_apache:
    needs: run_ansible_lint
    runs-on: self-hosted
    steps:
     - name: Installing apache
       run: |
        workdir=“${GITHUB_WORKSPACE}”
        ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu -i $workdir/host_inventory $workdir/playbooks/apache-install.yml --private-key '/home/ubuntu/.ssh/gp-13-july-22.pem'
